# Generated by Django 5.1.7 on 2025-03-19 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0002_alter_solved_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solved",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="playground.question"
            ),
        ),
    ]
